"""Canonical observation and reconciliation model types."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime


@dataclass(frozen=True, slots=True)
class SourceProvenance:
    """Describes where an observation came from and when."""

    collector: str
    artifact_path: str
    run_id: str
    observed_at: datetime


@dataclass(frozen=True, slots=True)
class ServiceEvidence:
    """Service-level evidence from a scan."""

    port: int
    protocol: str = "tcp"
    service: str | None = None
    state: str | None = None


@dataclass(frozen=True, slots=True)
class DeviceObservation:
    """Canonical, source-attributed view of observed device evidence."""

    provenance: SourceProvenance
    ip: str | None = None
    mac: str | None = None
    hostname: str | None = None
    services: tuple[ServiceEvidence, ...] = ()
    first_seen_at: datetime | None = None
    last_seen_at: datetime | None = None


@dataclass(frozen=True, slots=True)
class Contradiction:
    """Conflict that could not be collapsed safely."""

    category: str
    detail: str
    related_observations: tuple[DeviceObservation, ...] = ()


@dataclass(frozen=True, slots=True)
class ProvisionalIdentity:
    """Identity generated by first-pass deterministic reconciliation."""

    identity_key: str
    ips: tuple[str, ...]
    macs: tuple[str, ...]
    hostnames: tuple[str, ...]
    services: tuple[ServiceEvidence, ...]
    observations: tuple[DeviceObservation, ...]
    discrepancies: tuple[Contradiction, ...] = ()


@dataclass(slots=True)
class ReconciliationResult:
    """Container for merged identities and unresolved conflicts."""

    identities: list[ProvisionalIdentity] = field(default_factory=list)
    discrepancies: list[Contradiction] = field(default_factory=list)
